### PR TITLE
Feature/emp3 android#86 continue edit draw camera

### PR DESCRIPTION
**Pull request by empbarney**

### CODE REVIEW

**Review by Ish-rivera — APPROVED** [review]

**Comment by mubinakhan** [comment]
Circle is acting up doesn't plot properly

**Comment by empbarney** [comment]
device-2017-03-22-141603

**Comment by empbarney** [comment]
device-2017-03-22-141913

**Comment by mubinakhan** [comment]
screenshot_20170322-134054 1

**Comment by mubinakhan** [comment]
screenshot_20170322-142310 1

**Comment by mubinakhan** [comment]
ers=[0: (775.0, 810.9)]), policyFlags=0x62000000
03-22 14:31:49.652  1127  1132 I art     : Wrote stack traces to '/data/anr/trac                                                                                                                                                                                               es.txt'
03-22 14:31:49.708  1153  1158 I art     : Wrote stack traces to '/data/anr/trac                                                                                                                                                                                               es.txt'
03-22 14:31:49.954   803   809 I art     : Wrote stack traces to '/data/anr/trac                                                                                                                                                                                               es.txt'
03-22 14:31:50.699  7968  7968 I Choreographer: Skipped 66 frames!  The applicat                                                                                                                                                                                               ion may be doing too much work on its main thread.
03-22 14:31:51.964   657   670 E ActivityManager: ANR in mil.emp3.test.emp3vv (m                                                                                                                                                                                               il.emp3.test.emp3vv/.ValidateAndVerify)
03-22 14:31:51.964   657   670 E ActivityManager: PID: 7968
03-22 14:31:51.964   657   670 E ActivityManager: Reason: Input dispatching time                                                                                                                                                                                               d out (Waiting to send non-key event because the touched window has not finished                                                                                                                                                                                                processing certain input events that were delivered to it over 500.0ms ago.  Wa                                                                                                                                                                                               it queue length: 39.  Wait queue head age: 5511.2ms.)
03-22 14:31:51.964   657   670 E ActivityManager: Load: 5.21 / 4.69 / 4.66
03-22 14:31:51.964   657   670 E ActivityManager: CPU usage from 25066ms to 0ms                                                                                                                                                                                                ago:
03-22 14:31:51.964   657   670 E ActivityManager:   68% 7968/mil.emp3.test.emp3v                                                                                                                                                                                               v: 63% user + 5.2% kernel / faults: 36418 minor
03-22 14:31:51.964   657   670 E ActivityManager:   5.7% 192/surfaceflinger: 2.5                                                                                                                                                                                               % user + 3.1% kernel / faults: 34548 minor
03-22 14:31:51.964   657   670 E ActivityManager:   4.9% 657/system_server: 3.1%                                                                                                                                                                                                user + 1.8% kernel / faults: 347 minor
03-22 14:31:51.964   657   670 E ActivityManager:   1% 8167/kworker/u:0: 0% user                                                                                                                                                                                                + 1% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.9% 211/mpdecision: 0% user                                                                                                                                                                                                + 0.9% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.9% 7328/kworker/u:1: 0% us                                                                                                                                                                                               er + 0.9% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.1% 6322/kworker/u:18: 0% u                                                                                                                                                                                               ser + 0.1% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.4% 8199/sensors.qcom: 0% u                                                                                                                                                                                               ser + 0.4% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.4% 6187/kworker/0:3: 0% us                                                                                                                                                                                               er + 0.4% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.3% 90/msmfb_commit_th: 0%                                                                                                                                                                                                user + 0.3% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.3% 7344/kworker/u:3: 0% us                                                                                                                                                                                               er + 0.3% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.2% 7869/adbd: 0% user + 0.                                                                                                                                                                                               2% kernel / faults: 104 minor
03-22 14:31:51.964   657   670 E ActivityManager:   0.2% 8240/kworker/1:0: 0.2%                                                                                                                                                                                                user + 0% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.2% 2329/wms.wms:TMISServic                                                                                                                                                                                               e: 0% user + 0.1% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.1% 178/logd: 0% user + 0.1                                                                                                                                                                                               % kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 766/sdcard: 0% user + 0%                                                                                                                                                                                                kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.1% 6556/kworker/0:0: 0% us                                                                                                                                                                                               er + 0.1% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.1% 8188/logcat: 0.1% user                                                                                                                                                                                                + 0% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0.1% 745/MC_Thread: 0% user                                                                                                                                                                                                + 0.1% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 155/ueventd: 0% user + 0%                                                                                                                                                                                                kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 803/com.android.systemui:                                                                                                                                                                                                0% user + 0% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 891/com.google.process.ga                                                                                                                                                                                               pps: 0% user + 0% kernel / faults: 323 minor
03-22 14:31:51.964   657   670 E ActivityManager:   0% 145/mmcqd/0: 0% user + 0%                                                                                                                                                                                                kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 189/healthd: 0% user + 0%                                                                                                                                                                                                kernel
03-22 14:31:51.964   657   670 E ActivityManager:   0% 1323/com.google.android.g                                                                                                                                                                                               ms: 0% user + 0% kernel / faults: 23 minor
03-22 14:31:51.964   657   670 E ActivityManager:  +0% 8248/kworker/1:2: 0% user                                                                                                                                                                                                + 0% kernel
03-22 14:31:51.964   657   670 E ActivityManager: 9.4% TOTAL: 7% user + 1.4% ker                                                                                                                                                                                               nel + 0.9% iowait + 0% softirq
03-22 14:31:51.964   657   670 E ActivityManager: CPU usage from 4068ms to 4593m                                                                                                                                                                                               s later:
03-22 14:31:51.964   657   670 E ActivityManager:   7.5% 657/system_server: 1.8%                                                                                                                                                                                                user + 5.6% kernel
03-22 14:31:51.964   657   670 E ActivityManager:     7.5% 670/ActivityManager:                                                                                                                                                                                                3.7% user + 3.7% kernel
03-22 14:31:51.964   657   670 E ActivityManager:   1.7% 6187/kworker/0:3: 0% us                                                                                                                                                                                               er + 1.7% kernel
03-22 14:31:51.964   657   670 E ActivityManager: 1.9% TOTAL: 0.9% user + 0.9% k                                                                                                                                                                                               ernel
03-22 14:31:52.028   657  7071 I OpenGLRenderer: Initialized EGL, version 1.4
03-22 14:32:18.526  1087  2709 I Keyboard.Facilitator.LanguageModelFlusher: run()
03-22 14:32:18.526  1087  2709 I Keyboard.Facilitator: flushDynamicLanguageModels()
03-22 14:32:18.589   891   891 I ConfigService: onCreate
03-22 14:32:22.834   196   196 E         : invalid crash request of size 4 (from pid=8199 uid=0)
03-22 14:32:23.067   657   717 W qcom_sensors_hal: hal_sensor1_data_cb: SENSOR1_MSG_TYPE_BROKEN_PIPE
03-22 14:32:23.126  8342  8342 E Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 2
03-22 14:32:23.126  8342  8342 E Sensors : sns_fsa_la.c(386):fsa: fflush failed, 9
03-22 14:32:23.127  8342  8342 E Sensors : sns_fsa_la.c(386):fsa: fflush failed, 9
03-22 14:32:23.158  8342  8345 W Sensors : sns_smr_la.c(446):smr_la: smr_apps_la_thread_main is starting, fd=11, sns_smr.en_rx_msg_ptr=b6f42a04
03-22 14:32:23.170  8342  8347 W Sensors : sns_sam_app.c(6827):sns_sam_reg_algo: Registering algo service 16, err 0
03-22 14:32:23.177  8342  8349 E Sensors : sns_debug_main.c(565):Debug Config File missing in EFS!
03-22 14:32:23.630   891   891 I ConfigService: onDestroy

**Comment by empbarney** [comment]
adb logcat -c
adb logcat > file

**Comment by mubinakhan** [comment]
[file.txt](https://github.com/missioncommand/emp3-android/files/862504/file.txt)

**Pull request merged**
