### PR TITLE
Issue-10 #comment Removed setVisibility method from IMapEngine as it was

### PR DESCRIPTION
**Pull request by empbarney**
never used and it couldn't be used in it current form.
Issue-10 #comment StoreageManager updated to call add/Remove features
instead.

### CODE REVIEW

**Review by Ish-rivera — APPROVED** [review]
Looks good.

**Comment by empbarney** [comment]
Testing instructions:
 Build branch: (bugfix/emp3-android#10-set-visibility-fails
Install Capability Tester and launch Map.
Start "Add Remove Get" Test, Add one overlay, add a circle to that overlay, "Locate" the circle.
Select "Update Feature" and select the Circle feature you added.
On the Popup:
   Select the parent overlay under "Parents" column.
   Tap the "visible" box to uncheck it. Tap on the "Update" next to the "visiblle" box.
   Circle should be gone from the map.

   Now chweck the "visible" box and select "Update" next to it and circle should again be shown on the map.

**Comment by mubinakhan** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\mubina.khan\Code2\emp3-android\3rdpartylibrary\google-maps-                   android-cmgn\build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':3rdpartylibrary:google-maps-android-cmgn                   '.
> Could not get unknown property 'di2eNexusUsername' for project ':3rdpartylibra                   ry:google-maps-android-cmgn' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                    option to get more log output.

BUILD FAILED

**Comment by mubinakhan** [comment]
Tested

**Pull request merged**
