### PR TITLE
Added new method to keep lines parallel when editing 2525C tactical g…

### PR DESCRIPTION
**Pull request by rsupnekar**
…raphic "Bridge or Gap"

### CODE REVIEW

**Comment by rsupnekar** [comment]
Fix was tested by pulling control points, one at a time.  In each case, the lines stayed parallel.
screenshot from 2017-09-26 10-47-00

**Review by alberto-acevedo — APPROVED** [review]
Looks good.!

**Review by alberto-acevedo — APPROVED** [review]
Looks good.

**Review by alberto-acevedo — APPROVED** [review]
Changes look good.

**Review by alberto-acevedo — APPROVED** [review]

**Review by alberto-acevedo — APPROVED** [review]

**Comment by rsupnekar** [comment]
Review approval is in comments.  Reviewer was not able to approve with the submit button.

**Pull request merged**
