### PR TITLE
Reworked stylemaps and styles

### PR DESCRIPTION
**Pull request by rsupnekar**

### CODE REVIEW

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
see #160

**Review by ee11cbb19052e40b07aac0ca060c23ee — APPROVED** [review]

**Comment by rsupnekar** [comment]
To test, build branch and run test basic.

From the menu select Test, then Plot Test, then Plot KML.  You should see four buildings in four colors, viewed from the top.

**Comment by mubinakhan** [comment]
screenshot_20170418-173023 1

**Comment by mubinakhan** [comment]
Reintegrate

**Pull request merged**
