### PR TITLE
#258 add checksums to non snapshot releases

### PR DESCRIPTION
**Pull request by stevendlander**
Publish SHA-256 and MD5 checksums for the following artifacts:

* emp3-android-worldwind.apk
* emp3-android-sdk-core.apk

### CODE REVIEW

**Review by rsupnekar — APPROVED** [review]

**Comment by mubinakhan** [comment]
Matt please see the following error message.

 What went wrong:
Execution failed for task ':emp3-android-sdk-core:publishNebulaPublicationToMave           nLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
   > Invalid publication 'nebula': artifact file does not exist: 'C:\Users\mubin           a.khan\Code2\emp3-android\sdk\sdk-core\apk\build\outputs\apk\emp3-android-sdk-co           re-apk-release-unsigned.apk.md5'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug            option to get more log output.

BUILD FAILED in 38m 58s
403 actionable tasks: 403 executed

**Comment by mubinakhan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToLocal' not found in root project 'emp3-android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 31s

**Comment by mubinakhan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':emp3-android-sdk-core:publishNebulaPublicationToMavenLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
   > Invalid publication 'nebula': artifact file does not exist: 'C:\Users\mubina.khan\Code2\emp3-android\sdk\sdk-core\apk\build\outputs\apk\emp3-android-sdk-core-apk-release-unsigned.apk.md5'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 6s
16 actionable tasks: 8 executed, 8 up-to-date

**Comment by mubinakhan** [comment]
[emp3-android-sdk-core-apk-debug.txt](https://github.com/missioncommand/emp3-android/files/1188765/emp3-android-sdk-core-apk-debug.txt)
[emp3-android-sdk-core-apk-release-unsigned.txt](https://github.com/missioncommand/emp3-android/files/1188766/emp3-android-sdk-core-apk-release-unsigned.txt)

**Comment by mubinakhan** [comment]
Reintegrate

**Pull request merged**
