### PR TITLE
Bugfix/#142 polygon too many dots

### PR DESCRIPTION
**Pull request by Ish-rivera**
see #142

### CODE REVIEW

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Looks like the bug is still there:
bandicam 2017-04-12 16-21-44-846

I would suggest not using the artificial delay as part of the solution. It feels forced and unnatural.

**Comment by Ish-rivera** [comment]
I found the bug and corrected it.

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
The new fix looks good; I can't reproduce the extra dots. Can you remove the artificial delay now?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
> Can you remove the artificial delay now?

Or minimize the delay or allow it to be configurable?

**Review by ee11cbb19052e40b07aac0ca060c23ee — APPROVED** [review]
Looks good

**Pull request merged**
