### PR TITLE
#36 add cmapi jar

### PR DESCRIPTION
**Pull request by rsupnekar**

### CODE REVIEW

**Comment by stevendlander** [comment]
Are you planning on merging master in to fix the conflicts, or is this PR now no longer needed?

**Comment by rsupnekar** [comment]
We don't use master, we use development branch.  This reverts the changes related to DI2E access

**Review by rsupnekar — COMMENTED** [review]
The version number should be 2.7.1 not 2.8.1

**Review by matt-miller-rgi — APPROVED** [review]

**Comment by rsupnekar** [comment]
Removed as this was handled by another branch release/v2.7.1

**Pull request closed without merging**
